# Site settings
title: "Raúl San Martín"
description: "¡Hola! Soy un estudiante de Ingeniería de Telecomunicaciones y desarrollador que vive en España."
url: "https://raulsanmartin.es"
language: es
logo_url: "/images/logo.png"
logo_alt: "/images/logo_alt.png"
favicon: "/favicon.ico"
author: "Raúl San Martín Aniceto"
permalink: /:categories/:title/
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Paginate blog
paginate: 6
paginate_path: "blog/page:num"
post-preview-words: 298

# Categories and tags pages
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Theme fields
hola:
  background: "/images/hero-bg.jpg"
  contact_bg: "/images/contact-bg.jpg"

# Social settings
social:
  - title: Github
    icon: "fa fa-github"
    link: "https://github.com/MrAnnix"
  - title: Twitter
    icon: "fa fa-twitter"
    link: "https://twitter.com/MrAnnix"
  - title: Linkedin
    icon: "fa fa-linkedin"
    link: "https://www.linkedin.com/in/raul-san-martin-aniceto"
  - title: Contacto
    icon: "fa fa-envelope"
    smoothscroll: yes
    link: "/#contact"

feed: yes
