# Site settings
title: Raúl San Martín
description: ¡Hola! Soy un estudiante de Ingeniería de Telecomunicaciones y desarrollador que vive en España.
url: https://raulsanmartin.es
logo_url: /images/logo.png
logo_alt: /images/logo_alt.png
favicon: /favicon.ico
logo_alt:
permalink: pretty
author: Raúl San Martín Aniceto

#plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme fields
hola:
  background:
  text:

# Social settings
github: http://facebook.com
twitter: http://twitter.com
linkedin: http://instagram.com
email: http://youtube.com

feed: yes
