# Site settings
title: "Raúl San Martín"
description: "¡Hola! Soy un estudiante de Ingeniería de Telecomunicaciones y desarrollador que vive en España."
url: "https://raulsanmartin.es"
language: es
logo_url: "/images/logo.png"
logo_alt: "/images/logo_alt.png"
favicon: "/favicon.ico"
author: "Raúl San Martín Aniceto"
permalink: pretty

#plugins
plugins:
#  - jekyll-feed
#  - jekyll-sitemap

# Theme fields
hola:
  background: "/images/hero-bg.jpg"
  contact_bg: "/images/contact-bg.jpg"

# Social settings
social:
  - title: github
    icon: "im im-github"
    link: "https://github.com/MrAnnix"

  - title: twitter
    icon: "im im-twitter"
    link: "https://twitter.com/MrAnnix"

  - title: linkedin
    icon: "im im-linkedin"
    link: "https://www.linkedin.com/in/raul-san-martin-aniceto"

  - title: email
    icon: "im im-mail"
    smoothscroll: yes
    link: "/#contact"

feed: yes
